import os


class Config:
    SQLALCHEMY_DATABASE_URI = "sqlite:///example_2.db"
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    FILEBASE_ENDPOINT = os.getenv("FILEBASE_ENDPOINT")
    FILEBASE_ACCESS_KEY = os.getenv("FILEBASE_ACCESS_KEY")
    FILEBASE_SECRET_KEY = os.getenv("FILEBASE_SECRET_KEY")
    FILEBASE_BUCKET = os.getenv("FILEBASE_BUCKET")
